services:
  web: 
    build:
      context: app
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD='123'
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
